###VERIFICAR SE O ENDPOINT HEALTH (GET) RETORNA 200
###VERIFICAR SE O ENDPOINT V1/CATEGORIZE RETORNA 200 QUANDO RECEBE JSON VALIDO
###VERIFICAR SE O ENDPOINT V1/CATEGORIZE RETORNA 400 QUANDO RECEBE JSON INVALIDO
###VERIFICAR SE A PREDIÇÃO COM JSON VALIDO RETORN UMA LISTA COM TAMANHO 500